export default [ { id: 0, name: 'Amakna' },
  { id: 1, name: "L'île des Wabbits" },
  { id: 2, name: "L'île de Moon" },
  { id: 3, name: 'Prison' },
  { id: 4, name: 'Tainéla' },
  { id: 5, name: 'Sufokia' },
  { id: 6, name: 'Forêt des Abraknydes' },
  { id: 7, name: 'Bonta' },
  { id: 8, name: 'Plaine de Cania' },
  { id: 11, name: 'Brâkmar' },
  { id: 12, name: 'Landes de Sidimote' },
  { id: 13, name: 'Territoire des Dopeuls' },
  { id: 14, name: 'Village des Brigandins' },
  { id: 15, name: 'Foire du Trool' },
  { id: 18, name: 'Astrub' },
  { id: 19, name: 'Pandala Neutre' },
  { id: 20, name: 'Pandala Eau' },
  { id: 21, name: 'Pandala Terre' },
  { id: 22, name: 'Pandala Feu' },
  { id: 23, name: 'Pandala Air' },
  { id: 24, name: 'Pandala Donjon' },
  { id: 26, name: 'Le labyrinthe du Dragon Cochon' },
  { id: 27, name: 'Donjon Abraknyde' },
  { id: 28, name: 'Montagne des Koalaks' },
  { id: 29, name: 'Donjon des Tofus' },
  { id: 30, name: "L'île du Minotoror" },
  { id: 31, name: 'Centre du labyrinthe du Minotoror' },
  { id: 32, name: 'La bibliothèque du Maître Corbac' },
  { id: 33, name: 'Donjon des Canidés' },
  { id: 34, name: 'Caverne du Koulosse' },
  { id: 36, name: 'Sanctuaire des Familiers' },
  { id: 37, name: 'Donjon des Craqueleurs' },
  { id: 38, name: 'Serveur de test' },
  { id: 39, name: 'Donjon des Bworks' },
  { id: 40, name: 'Donjon des Scarafeuilles' },
  { id: 41, name: 'Donjon des Champs' },
  { id: 42, name: 'Île de Nowel' },
  { id: 43, name: 'Donjon du Dragon Cochon' },
  { id: 44, name: 'Donjon des Dragoeufs' },
  { id: 45, name: 'Incarnam' },
  { id: 46, name: "Île d'Otomaï" },
  { id: 47, name: 'Village des Zoths' },
  { id: 48, name: 'Île de Frigost' },
  { id: 49, name: 'Île de Sakaï' },
  { id: 50, name: 'Archipel de Vulkania' },
  { id: 52, name: 'Îlot Rifique' },
  { id: 53, name: "Île d'Orado" },
  { id: 54, name: 'Hall des Valeureux' },
  { id: 99999, name: 'Position Inconnue' }  ]
