export default [ { id: 1, areaId: 0, name: 'Port de Madrestam' },
  { id: 2, areaId: 0, name: 'La montagne des Craqueleurs' },
  { id: 3, areaId: 0, name: 'Le champ des Ingalsses' },
  { id: 4, areaId: 0, name: "La forêt d'Amakna" },
  { id: 5, areaId: 0, name: 'Le coin des Bouftous' },
  { id: 6, areaId: 0, name: 'Le cimetière' },
  { id: 7, areaId: 0, name: 'Les cryptes' },
  { id: 8, areaId: 0, name: 'Campement des Bworks' },
  { id: 9, areaId: 0, name: 'La forêt maléfique' },
  { id: 10, areaId: 0, name: 'Le village' },
  { id: 11, areaId: 0, name: 'Territoire des Porcos' },
  { id: 12, areaId: 0, name: 'La péninsule des gelées' },
  { id: 22, areaId: 0, name: 'Bord de la forêt maléfique' },
  { id: 23, areaId: 0, name: "La presqu'île des Dragoeufs" },
  { id: 25, areaId: 1, name: 'Souterrains des Wabbits' },
  { id: 27, areaId: 0, name: "Côte d'Asse" },
  { id: 29, areaId: 0, name: 'Souterrains' },
  { id: 30, areaId: 4, name: 'Le berceau' },
  { id: 31, areaId: 0, name: 'Le marécage' },
  { id: 32, areaId: 5, name: 'Sufokia' },
  { id: 33, areaId: 6, name: 'Forêt des Abraknydes' },
  { id: 34, areaId: 3, name: 'Prison' },
  { id: 38, areaId: 8, name: 'Plaine de Cania' },
  { id: 39, areaId: 0, name: 'Repaire des roublards' },
  { id: 43, areaId: 7, name: 'Fortification de Bonta' },
  { id: 44, areaId: 7, name: 'Quartier des Boulangers' },
  { id: 46, areaId: 7, name: 'Quartier des Bouchers' },
  { id: 47, areaId: 7, name: 'Quartier des Forgerons' },
  { id: 48, areaId: 7, name: 'Quartier des Bûcherons' },
  { id: 49, areaId: 7, name: 'Quartier des Bricoleurs' },
  { id: 50, areaId: 7, name: 'Quartier des Tailleurs' },
  { id: 51, areaId: 7, name: 'Quartier des Bijoutiers' },
  { id: 54, areaId: 8, name: 'Massif de Cania' },
  { id: 55, areaId: 8, name: 'Pénates du Corbac' },
  { id: 56, areaId: 8, name: 'Forêt de Cania' },
  { id: 57, areaId: 12, name: 'Landes de Sidimote' },
  { id: 59, areaId: 8, name: 'Cimetière de Bonta' },
  { id: 61, areaId: 12, name: 'Cimetière des Torturés' },
  { id: 62, areaId: 13, name: 'Village des Dopeuls' },
  { id: 68, areaId: 8, name: 'Les Champs de Cania' },
  { id: 69, areaId: 8, name: 'Bois de Litneg' },
  { id: 70, areaId: 8, name: 'Plaines Rocheuses' },
  { id: 71, areaId: 12, name: 'Gisgoul, le village dévasté' },
  { id: 73, areaId: 7, name: 'Égouts de Bonta' },
  { id: 75, areaId: 11, name: 'Égouts de Brâkmar' },
  { id: 76, areaId: 14, name: 'Village des Brigandins' },
  { id: 77, areaId: 0, name: 'La gelaxième dimension' },
  { id: 78, areaId: 0, name: 'La gelaxième dimension (royale)' },
  { id: 82, areaId: 4, name: 'Donjon des Bouftous' },
  { id: 84, areaId: 15, name: 'Foire du Trooll' },
  { id: 92, areaId: 18, name: "Contour d'Astrub" },
  { id: 93, areaId: 2, name: 'La plage de Moon' },
  { id: 94, areaId: 12, name: 'Donjon du Bworker' },
  { id: 95, areaId: 18, name: "Cité d'Astrub" },
  { id: 96, areaId: 18, name: "Exploitation minière d'Astrub" },
  { id: 97, areaId: 18, name: "Forêt d'Astrub" },
  { id: 98, areaId: 18, name: "Champs d'Astrub" },
  { id: 99, areaId: 18, name: "Souterrains d'Astrub" },
  { id: 100, areaId: 18, name: "Souterrains profonds d'Astrub" },
  { id: 101, areaId: 18, name: 'Le coin des Tofus' },
  { id: 102, areaId: 0, name: 'Le champ du repos' },
  { id: 103, areaId: 0, name: 'Territoire des Bandits' },
  { id: 105, areaId: 19, name: 'Pandala Neutre' },
  { id: 106, areaId: 20, name: "Bordure d'Akwadala" },
  { id: 107, areaId: 22, name: 'Bordure de Feudala' },
  { id: 108, areaId: 23, name: "Bordure d'Aerdala" },
  { id: 109, areaId: 21, name: 'Bordure de Terrdala' },
  { id: 115, areaId: 23, name: "Village d'Aerdala" },
  { id: 116, areaId: 22, name: 'Village de Feudala' },
  { id: 117, areaId: 20, name: "Village d'Akwadala" },
  { id: 118, areaId: 21, name: 'Village de Terrdala' },
  { id: 119, areaId: 19, name: 'Village de Pandala' },
  { id: 124, areaId: 24, name: 'Caverne des Bulbes' },
  { id: 125, areaId: 24, name: 'Repaire des Pandikazes' },
  { id: 133, areaId: 24, name: 'Donjon des Kitsounes' },
  { id: 143, areaId: 19, name: 'Pont de Pandala' },
  { id: 144, areaId: 24, name: 'Donjon des Firefoux' },
  { id: 152, areaId: 19, name: "L'île de Grobe" },
  { id: 154, areaId: 43, name: 'Antre du Dragon Cochon' },
  { id: 161, areaId: 1, name: 'Île de la Cawotte' },
  { id: 162, areaId: 1, name: 'Îlot de Waldo' },
  { id: 163, areaId: 1, name: 'Îlot des Tombeaux' },
  { id: 164, areaId: 1, name: 'Îlot de la Couronne' },
  { id: 165, areaId: 2, name: 'La jungle profonde de Moon' },
  { id: 166, areaId: 2, name: 'Le chemin vers Moon' },
  { id: 167, areaId: 2, name: 'Le bateau pirate' },
  { id: 168, areaId: 6, name: 'Forêt des Abraknydes Sombres' },
  { id: 169, areaId: 6, name: 'Orée de la forêt des Abraknydes' },
  { id: 170, areaId: 0, name: 'Plaine des Scarafeuilles' },
  { id: 171, areaId: 19, name: 'Forêt de Pandala' },
  { id: 173, areaId: 18, name: "Prairies d'Astrub" },
  { id: 175, areaId: 27, name: 'Donjon des Abraknydes' },
  { id: 178, areaId: 8, name: 'Plaine des Porkass' },
  { id: 179, areaId: 0, name: 'Le coin des Boos' },
  { id: 180, areaId: 0, name: "Le château d'Amakna" },
  { id: 181, areaId: 0, name: "Souterrains du Château d'Amakna" },
  { id: 182, areaId: 28, name: 'Village des Eleveurs' },
  { id: 200, areaId: 26, name: 'Labyrinthe du Dragon Cochon' },
  { id: 201, areaId: 29, name: 'Donjon des Tofus' },
  { id: 209, areaId: 30, name: "L'île du Minotoror" },
  { id: 99999, areaId: 999, name: "Position Inconnue" }]
